# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# Colours, Colours, Colours

if [ -e /usr/share/terminfo/x/xterm-256color ]; then
        export TERM='xterm-256color'
else
        export TERM='xterm-color'
fi

# User specific environment and startup programs
export HISTFILESIZE= HISTSIZE=
export HISTTIMEFORMAT="%d/%m/%y %T "
export HISTFILE="${HOME}/.bash_history.$(hostname)"

export PATH=/home/mpiuser/bin:/scratch/mpiuser/bin:$PATH
export LD_LIBRARY_PATH=/home/mpiuser/lib/openmpi:/home/mpiuser/lib:/scratch/mpiuser/lib/openmpi:/scratch/mpiuser/lib:$LD_LIBRARY_PATH
